import eslint from '@eslint/js';
import stylistic from '@stylistic/eslint-plugin';
import { defineConfigWithVueTs, vueTsConfigs } from '@vue/eslint-config-typescript';
import { globalIgnores } from 'eslint/config';
import checkFile from 'eslint-plugin-check-file';
import compat from 'eslint-plugin-compat';
import eslintPluginJestDom from 'eslint-plugin-jest-dom';
import preferArrow from 'eslint-plugin-prefer-arrow-functions';
import simpleImportSort from 'eslint-plugin-simple-import-sort';
import eslintPluginTestingLibrary from 'eslint-plugin-testing-library';
import eslintPluginVue from 'eslint-plugin-vue';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import oxlint from 'eslint-plugin-oxlint';

export default defineConfigWithVueTs(
  eslint.configs.recommended,
  tseslint.configs.strictTypeChecked,
  tseslint.configs.stylisticTypeChecked,
  ...eslintPluginVue.configs['flat/recommended'],
  compat.configs['flat/recommended'],
  stylistic.configs.customize({
    indent: 2,
    quotes: 'single',
    semi: true,
    jsx: true,
  }),
  vueTsConfigs.recommended,
  globalIgnores([
    '**/node_modules/**',
    '**/autogenerated/**',
    '**/archive/**',
    '**/dist/**',
    '**/dist-ssr/**',
    '**/coverage/**',
    './vitest.globalSetup.ts',
  ]),
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    files: ['**/*.{js,mjs,jsx,ts,mts,tsx,vue}'],
    rules: {
      '@typescript-eslint/restrict-template-expressions': ['error', {
        allowNumber: true,
        allowNever: true,
      }],
    },
  },
  {
    files: [
      '**/*.test.{js,mjs,jsx,ts,mts,tsx}',
      './src/tests/**/*.ts',
      './src/mocks/**/*.ts',
    ],
    ignores: ['src/tests/e2e/**/*'],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.es2021,
        ...globals.node,
      },
      ecmaVersion: 'latest',
      sourceType: 'module',
    },
    plugins: {
      'jest-dom': eslintPluginJestDom,
      'testing-library': eslintPluginTestingLibrary,
    },
    ...eslintPluginJestDom.configs['flat/all'],
    ...eslintPluginTestingLibrary.configs['flat/vue'],
    rules: {
      '@typescript-eslint/unbound-method': 'off',
      '@typescript-eslint/no-dynamic-delete': 'off',
    },
  },
  {
    files: ['**/*.{js,mjs,jsx,ts,mts,tsx,vue}'],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.es2021,
        ...globals.node,
      },
      ecmaVersion: 'latest',
      sourceType: 'module',
    },
    plugins: {
      'prefer-arrow': preferArrow,
      '@stylistic': stylistic,
      'check-file': checkFile,
      'simple-import-sort': simpleImportSort,
    },
    rules: {
      '@stylistic/arrow-parens': ['error', 'always'],
      '@stylistic/brace-style': ['error', '1tbs'],
      '@stylistic/max-len': ['error', {
        code: 80,
        ignoreComments: true,
        ignoreStrings: true,
        ignoreTemplateLiterals: true,
        ignorePattern: 'd=.*|<!--.*|class=.*|src=.*',
      }],
      'check-file/filename-naming-convention': ['error', {
        'src/**/*.!(test).js': 'KEBAB_CASE',
        'src/composables/*.js': 'CAMEL_CASE',
      },
      {
        ignoreMiddleExtensions: true,
      }],
      '@typescript-eslint/no-unused-vars': ['error', {
        varsIgnorePattern: '_.*',
        argsIgnorePattern: '^_',
      }],
      'check-file/folder-naming-convention': ['error', {
        'src/modules/*/': 'PASCAL_CASE',
      }],

      'func-style': [
        'error',
        'expression',
        { allowArrowFunctions: true },
      ],
      'no-console': [
        'error',
        {
          allow: ['warn', 'error', 'info'],
        },
      ],
      'vue/component-name-in-template-casing': ['error', 'PascalCase'],
      'vue/html-self-closing': ['error', {
        html: {
          void: 'always',
          normal: 'never',
        },
      }],
      'vue/singleline-html-element-content-newline': 0,
      'vue/no-v-html': 0,
      'vue/max-attributes-per-line': ['error', {
        singleline: {
          max: 3,
        },
        multiline: {
          max: 1,
        },
      }],

      // rules from htmlacademy config

      // Possible Errors
      // https://eslint.org/docs/rules/#possible-errors
      // ---------------------------------------------
      'no-template-curly-in-string': 'error',
      'no-use-before-define': ['error', { functions: false }],
      // Suggestions
      // https://eslint.org/docs/rules/#suggestions
      // ---------------------------------------------
      'accessor-pairs': 'error',
      'arrow-body-style': ['error', 'as-needed'],
      'camelcase': 'error',
      'eqeqeq': ['error', 'always'],
      'no-alert': 'error',
      'no-nested-ternary': 'error',
      'no-return-assign': 'error',
      'no-shadow': ['error', { hoist: 'all' }],
      'no-unneeded-ternary': 'error',
      'no-unused-expressions': 'error',
      'no-useless-concat': 'error',
      'no-useless-return': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      'prefer-template': 'error',
      'radix': 'error',
      'strict': ['error', 'global'],
      // end rules from htmlacademy config

      'prefer-arrow/prefer-arrow-functions': [
        'error',
        {
          disallowPrototype: true,
          singleReturnOnly: false,
          classPropertiesAllowed: false,
        },
      ],
      'prefer-arrow-callback': [
        'error',
        { allowNamedFunctions: true },
      ],
      'simple-import-sort/imports': 'error',
      'simple-import-sort/exports': 'error',
    },
  },
  ...oxlint.buildFromOxlintConfigFile('./.oxlintrc.json'),
);
