import legacy from '@vitejs/plugin-legacy';
import vue from '@vitejs/plugin-vue';
import removeAttr from 'remove-attr';
import { visualizer } from 'rollup-plugin-visualizer';
import { fileURLToPath, URL } from 'url';
import { defineConfig } from 'vite';
// import eslint from 'vite-plugin-eslint2';
// import stylelint from 'vite-plugin-stylelint';
// import oxlint from 'vite-plugin-oxlint';

// https://vitejs.dev/config/
export default defineConfig(({ mode }) =>
  ({
    server: {
      port: 8070,
      hmr: {
        // clientPort: 443,
        overlay: false,
      },
    },
    resolve: {
      alias: {
        '~': fileURLToPath(new URL('./', import.meta.url)),
        '@': fileURLToPath(new URL('./src', import.meta.url)),
        '@scss': fileURLToPath(new URL('./src/assets/scss', import.meta.url)),
      },
    },
    test: {
      environment: 'jsdom',
      exclude: ['node_modules', './src/tests/e2e/*'],
      setupFiles: ['./vitest.setup.js'],
      globalSetup: './vitest.globalSetup.ts',
      globals: true,
      mockReset: true,
      env: {
        DEV: false,
      },
      coverage: {
        enabled: true,
        reporter: 'html',
        provider: 'v8',
        exclude: [
          './src/components/icons/*',
          './src/components/animations/*',
          './src/types/*',
          './src/locales/*',
          'dist',
          'node_modules',
        ],
      },
    },
    plugins: [
      vue(),
      legacy(),
      removeAttr({
        extensions: [mode === 'test' ? '' : 'vue'],
        attributes: ['data-testid'],
      }),
      visualizer({
        filename: './autogenerated/stats.html',
      }),
    ],
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: `@use "@/assets/scss/main.scss" as *;`,
          api: 'modern-compiler',
        },
      },
    },
  }));
