import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { RouteRecordRaw } from 'vue-router';

import { routes as mainRoutes } from '../src/router/routes';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Transforms routes to use template components for testing
 */
const transformRoutesForTesting = (
  routeList: RouteRecordRaw[],
): RouteRecordRaw[] =>
  routeList.map((route) => {
    const transformedRoute = { ...route };

    // Replace component with template if it exists
    if (route.component) {
      if (route.name && typeof route.name === 'string') {
        transformedRoute.component = { template: route.name };
      } else {
        transformedRoute.component = { template: 'UnnamedRoute' };
      }
      // Add template property for test component
    }

    // Replace all beforeEnter functions with null
    if (route.beforeEnter) {
      transformedRoute.beforeEnter = undefined;
    }

    // Recursively transform children
    if (route.children) {
      transformedRoute.children = transformRoutesForTesting(route.children);
    }

    return transformedRoute;
  });

export const generateTestRoutes = async () => {
  try {
    const outputPath = path.resolve(__dirname, '../autogenerated/test-routes.ts');

    // Transform routes for testing using direct imports - much simpler!
    const testRoutes = transformRoutesForTesting(
      [...mainRoutes],
    );

    // Generate the test routes file content
    const testRoutesContent = `// This file is auto-generated by scripts/generate-test-routes.ts
// DO NOT MODIFY MANUALLY - it will be overwritten

import type { NamedRouteRecordRaw } from 'vue-routes-to-types';

export const testRoutes = ${JSON.stringify(testRoutes, null, 2)
  .replace(/"template":\s*"([^"]+)"/g, 'template: "<div>$1</div>"')} as const satisfies NamedRouteRecordRaw[];
`;

    // Write the test routes file
    await fs.writeFile(outputPath, testRoutesContent);

    console.info('✅ Test routes generated successfully at autogenerated/test-routes.ts');
  } catch (error) {
    console.error('❌ Error generating test routes:', error);
    process.exit(1);
  }
};
